# CI build file
language: python
python:
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install mock
script:
  - pytest --cov=grifter --cov-report=term-missing
after_success:
  - coveralls
