---
hosts:
  - name: "sw01"
    vagrant_box:
      name: "arista/veos"
      version:
      provider:

    insert_ssh_key: False
    synced_folder:

    provider_config:
      nic_adapter_count: 12
      disk_bus: "ide"
      cpus: 2
      memory: 2048

    interfaces:
      - name: "eth1"
        local_port: 1
        remote_host: "sw02"
        remote_port: 1
      - name: "eth2"
        local_port: 2
        remote_host: "sw02"
        remote_port: 2

  - name: "sw02"
    vagrant_box:
      name: "arista/veos"
      version:
      provider:

    insert_ssh_key: False
    synced_folder:

    provider_config:
      nic_adapter_count: 12
      disk_bus: "ide"
      cpus: 2
      memory: 2048

    interfaces:
      - name: "eth1"
        local_port: 1
        remote_host: "sw01"
        remote_port: 1
      - name: "eth2"
        local_port: 2
        remote_host: "sw01"
        remote_port: 2